# Generated by Django 2.2.11 on 2020-03-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('mode', models.BooleanField()),
                ('full_name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=100)),
                ('birth_date', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('ec_name', models.CharField(max_length=100)),
                ('ec_ic_number', models.CharField(max_length=100)),
                ('ec_relationship', models.CharField(max_length=100)),
                ('ec_phone', models.CharField(max_length=100)),
                ('ec_address', models.CharField(max_length=100)),
                ('general_condition', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('pulse', models.CharField(max_length=100)),
                ('BP', models.CharField(max_length=100)),
                ('resp', models.CharField(max_length=100)),
                ('spo2', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('biohazard_infectious_disease', models.CharField(max_length=100)),
                ('medical_history', models.CharField(max_length=100)),
                ('surgical_history', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(max_length=100)),
                ('own_medication', models.CharField(max_length=100)),
                ('denture', models.CharField(max_length=100)),
                ('admission_by', models.CharField(max_length=100)),
                ('date_discharge', models.CharField(max_length=100)),
            ],
        ),
    ]
