# Generated by Django 2.2.11 on 2020-03-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200330_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mode',
            field=models.CharField(choices=[('A', 'Ambulance'), ('O', 'Own Transport')], max_length=100),
        ),
    ]
