# Generated by Django 2.2.11 on 2020-03-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20200330_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mode',
            field=models.CharField(choices=[('ambulance', 'Ambulance'), ('own', 'Own Transport')], max_length=100),
        ),
    ]
