# Generated by Django 2.2.11 on 2020-03-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200330_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Ambulance'), (1, 'Own Transport')], max_length=100),
        ),
    ]
