# Generated by Django 2.2.11 on 2020-03-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20200331_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cannulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
                ('cannula_cbd_ryles_tube', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('done_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargesSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
                ('amount_unit', models.CharField(max_length=100)),
                ('given_by', models.CharField(max_length=100)),
            ],
        ),
    ]
