# Generated by Django 2.2.11 on 2020-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_cannulation_chargessheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForHomeCareHomeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=100)),
                ('date_time_of_appointment', models.CharField(max_length=100)),
                ('hospital_clinic', models.CharField(max_length=100)),
                ('treatment_order', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='birth_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='date_discharge',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
