# Generated by Django 2.2.11 on 2020-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20200401_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ic_number',
            field=models.IntegerField(),
        ),
    ]
