# Generated by Django 2.2.11 on 2020-04-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20200401_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='ec_ic_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationforhomecarehomeleave',
            name='ic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icnumber_homeleave', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_appointment', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icnumber_appointment', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='cannulation',
            name='ic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icnumber_cannulation', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='chargessheet',
            name='ic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icnumber_chargessheet', to='patient.Patient'),
        ),
    ]
