# Generated by Django 2.2.11 on 2020-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20200401_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pulse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='resp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='admission',
            name='spo2',
            field=models.IntegerField(),
        ),
    ]
