# Generated by Django 2.2.11 on 2020-04-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20200401_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='full_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullname', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='ic_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icnumber', to='patient.Patient'),
        ),
    ]
